name: thai59
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fluro: ^1.5.1
  fluttertoast: ^8.0.8
  flutter_screenutil: ^5.0.0
  dio: ^4.0.0
  package_info_plus: "^1.3.0"
  uuid: 3.0.5
  shared_preferences: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0



flutter:
  uses-material-design: true
  assets:
    - assets/images/img_welcome.png
    - assets/images/img_bg.png
    - assets/images/icon_about.png
    - assets/images/icon_arror.png
    - assets/images/icon_back.png
    - assets/images/icon_call.png
    - assets/images/icon_exit.png
    - assets/images/icon_info.png
    - assets/images/icon_loan.png
flutter_intl:
  enabled: true


